// <auto-generated />
namespace SIAM.Data.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class siamr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(siamr));
        
        string IMigrationMetadata.Id
        {
            get { return "201501070017282_siamr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
